/*
 Navicat Premium Data Transfer

 Source Server         : dev-act
 Source Server Type    : MySQL
 Source Server Version : 50625
 Source Host           : mysql.dev.xianglin.com:3306
 Source Schema         : xlactdb

 Target Server Type    : MySQL
 Target Server Version : 50625
 File Encoding         : 65001

 Date: 09/01/2019 13:42:27
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for act_activity
-- ----------------------------
DROP TABLE IF EXISTS `act_activity`;
CREATE TABLE `act_activity`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ACTIVITY_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动标签',
  `ACTIVITY_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动名称',
  `START_DATE` datetime(0) NULL DEFAULT NULL COMMENT '活动开始时间',
  `EXPIRE_DATE` datetime(0) NULL DEFAULT NULL COMMENT '活动结束日期',
  `ACTIVITY_MAIN_IMG` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动主图',
  `ACTIVITY_MAIN_IMG_DEST` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动主图跳转路径',
  `ACTIVITY_RULE` varchar(5000) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动规则',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 36 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '活动定义表 AMOUNT = 1000 SELECT = LOW INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_activity_config
-- ----------------------------
DROP TABLE IF EXISTS `act_activity_config`;
CREATE TABLE `act_activity_config`  (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT,
  `ACTIVITY_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '活动code',
  `CONFIG_KEY` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '配置key',
  `CONFIG_VALUE` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `CONFIG_DESC` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '字段说明',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `UK_ACT_CONFIG_KEY`(`CONFIG_KEY`, `ACTIVITY_CODE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 175 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '活动配置' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_annual_report
-- ----------------------------
DROP TABLE IF EXISTS `act_annual_report`;
CREATE TABLE `act_annual_report`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户partyId',
  `USER_TYPE` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '用户类型',
  `JOIN_DATE` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '加入时间',
  `FIRST_ARTICLE` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数次发布微博时间',
  `GOLD_RANKING` int(11) NULL DEFAULT NULL COMMENT '金币收入排名',
  `GOLD_TOTLE` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '总金币收入',
  `TOTAL_ARTICLE` int(11) NULL DEFAULT 0 COMMENT '总微博数',
  `TOTAL_COMMENTS` int(11) NULL DEFAULT NULL COMMENT '得到的总评论数',
  `TOTAL_PRAISE` int(11) NULL DEFAULT 0 COMMENT '收到点赞数',
  `TOTAL_INVITE` int(11) NULL DEFAULT NULL COMMENT '总邀请好友数',
  `TOTAL_ACTIVITY` int(11) NULL DEFAULT NULL COMMENT '总参与活动数',
  `TOTAL_FOLLOW` int(11) NULL DEFAULT 0 COMMENT '总粉丝数',
  `TOTAL_ATTENTION` int(11) NULL DEFAULT 0 COMMENT '总关注数',
  `LATELY_ACTIVITY` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '最近参与的三个活动',
  `GROW_ARTICLE` int(11) NULL DEFAULT 0 COMMENT '增加微博数',
  `GROW_FOLLOW` int(11) NULL DEFAULT 0 COMMENT '增加粉丝数',
  `GROW_PRAISE` int(11) NULL DEFAULT 0 COMMENT '增加点赞数',
  `GROW_ATTENTION` int(11) NULL DEFAULT 0 COMMENT '增加关注数',
  `APP_RANK` int(11) NULL DEFAULT 0 COMMENT 'app活跃排名',
  `NODE_PROVINCE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '省份',
  `NODE_PROVINCE_COUNT` int(8) NULL DEFAULT NULL COMMENT '同省站长人数',
  `NODE_JOIN` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '加盟小站时间',
  `NODE_DEPOSIT` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '总存款',
  `NODE_CARD_COUNT` int(11) NULL DEFAULT 0 COMMENT '总卡数',
  `NODE_RANK` int(11) NULL DEFAULT 0 COMMENT '排名',
  `ESHOP_RANK` int(11) NULL DEFAULT 0 COMMENT '电商排名',
  `ESHOP_DATE` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '加入电商日期',
  `ESHOP_COUNT` int(8) NULL DEFAULT 0 COMMENT '购物消费笔数',
  `ESHOP_AMOUNT` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '购物消费总额',
  `ESHOP_POWER_COUNT` int(8) NULL DEFAULT 0 COMMENT '花费水电煤笔数',
  `ESHOP_POWER_AMOUNT` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '生活服务类总额',
  `SOLAR_RANK` int(4) NULL DEFAULT 0 COMMENT '光伏排名',
  `SOLAR_DATE` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '开通光伏日期',
  `SOLAR_INCONE` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '总收益',
  `SOLAR_DAYS` int(8) NULL DEFAULT NULL COMMENT '正常运行天数',
  `SOLAR_TOTAL` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '总发电量',
  `MERCHANT_RANK` int(11) NULL DEFAULT 0 COMMENT '排名',
  `MERCHANT_DATE` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '电商开通时间',
  `MERCHANT_COUNT` int(11) NULL DEFAULT 0 COMMENT '总订单数',
  `MERCHANT_AMOUNT` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '总交易额',
  `LOAN_RANK` int(11) NULL DEFAULT 0 COMMENT '贷款排名',
  `LOAN_DATE` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '贷款开通日期',
  `LOAN_INVITE_COUNT` int(11) NULL DEFAULT 0 COMMENT '帮助贷款成功笔数',
  `LOAN_AMOUNT` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '总贷款金额',
  `INTEREST_DATE` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SHARE_TYPE` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '用户业绩类型',
  `SHARE_URL` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '分享图片地址',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL,
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT 'N',
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '2017年度年报' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_attendance_coin_award
-- ----------------------------
DROP TABLE IF EXISTS `act_attendance_coin_award`;
CREATE TABLE `act_attendance_coin_award`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `AWARD_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖励名称',
  `AWARD_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖励code 单表唯一',
  `TARGET_CUSTOMER_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户类型 连续登录、非连续登录：CONTINUOUS/DISCONTINUOUS',
  `AWARD_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖励类型 翻倍、不翻倍:MULTIPLY/UNMULTIPLY',
  `AWARD_TIMES` int(11) NULL DEFAULT NULL COMMENT '翻倍奖励类型的倍数',
  `SIGN_IN_ORDER_FLOOR_PERCENT` decimal(5, 2) NULL DEFAULT NULL COMMENT '打卡时间排序的百分比区间下限',
  `SIGN_IN_ORDER_CEIL_PERCENT` decimal(5, 2) NULL DEFAULT NULL COMMENT '打卡时间排序的百分比区间上限',
  `MIN_VALUE` decimal(15, 2) NULL DEFAULT NULL COMMENT '不翻倍奖励的奖励最小值',
  `MAX_VALUE` decimal(15, 2) NULL DEFAULT NULL COMMENT '不翻倍奖励的奖励最大值',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `AWARD_CODE`(`AWARD_CODE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 15 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '打卡赢金币奖励类型定义表 AMOUNT = 10000 SELECT = LOW INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_customer_acquire_contactinfo
-- ----------------------------
DROP TABLE IF EXISTS `act_customer_acquire_contactinfo`;
CREATE TABLE `act_customer_acquire_contactinfo`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `PARTY_ID` bigint(20) NULL DEFAULT NULL COMMENT 'PARTY_ID',
  `MOBILE_PHONE` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '手机号',
  `NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '姓名',
  `ADDRESS` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '详细地址',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 14 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '用户获奖联系信息 AMOUNT = 1000 SELECT = MEDIUM INSERT = MEDIUM UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_customer_acquire_record
-- ----------------------------
DROP TABLE IF EXISTS `act_customer_acquire_record`;
CREATE TABLE `act_customer_acquire_record`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `PARTY_ID` bigint(20) NULL DEFAULT NULL COMMENT 'PARTY_ID',
  `USER_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户姓名，冗余字段',
  `USER_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户类型',
  `ACTIVITY_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动标签',
  `MOBILE_PHONE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户手机号（冗余，仅用于展示获奖列表）',
  `HEAD_IMAGE_URL` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户头像 （冗余，仅用于展示获奖列表）',
  `ACTIVITY_FEE` decimal(16, 5) NULL DEFAULT NULL COMMENT '活动参与手续费',
  `PRIZE_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品',
  `PRIZE_VALUE` decimal(16, 5) NULL DEFAULT NULL COMMENT '奖品价值',
  `MEMC_CODE` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'code',
  `ACQUIRE_DATE` datetime(0) NULL DEFAULT NULL COMMENT '获奖时间',
  `SIGN_IN_DATE` datetime(0) NULL DEFAULT NULL COMMENT '打卡时间',
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '状态，不同的用户类型和不同的活动有不同的状态',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `INX#CAR#PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `INX#CAR#PARTY_ID#SI_DATE`(`PARTY_ID`, `SIGN_IN_DATE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5223 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '用户获奖记录 AMOUNT = 500000 SELECT = HIGH INSERT = MEDIUM UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_customer_prize
-- ----------------------------
DROP TABLE IF EXISTS `act_customer_prize`;
CREATE TABLE `act_customer_prize`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `CUSTOMER_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户类型',
  `PRIZE_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品',
  `AMOUNT` int(11) NULL DEFAULT NULL COMMENT '奖品个数',
  `AVAILABLE_AMOUNT` int(11) NULL DEFAULT NULL COMMENT '可用的奖品个数',
  `INITIAL_PROBABILITY` decimal(16, 15) NULL DEFAULT NULL COMMENT '初始概率',
  `ADD_PROBABILITY` decimal(16, 15) NULL DEFAULT NULL COMMENT '提升后概率',
  `MIN_VALUE` decimal(16, 5) NULL DEFAULT NULL,
  `MAX_VALUE` decimal(16, 5) NULL DEFAULT NULL,
  `REMAIN_VALUE` int(11) NULL DEFAULT NULL COMMENT '奖品值小数位保留位',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 106 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '奖品&用户类型定义 AMOUNT = 10000 SELECT = LOW INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_dynamic_pop_window
-- ----------------------------
DROP TABLE IF EXISTS `act_dynamic_pop_window`;
CREATE TABLE `act_dynamic_pop_window`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `EVENT_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '关联的弹窗code，类型为FROM_ACT',
  `PARTY_ID` bigint(20) UNSIGNED NOT NULL COMMENT 'partyId',
  `CONTENT` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '弹窗消息内容',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '动态活动弹窗表 AMOUNT = 1000 SELECT = HIGH INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_ext_prop
-- ----------------------------
DROP TABLE IF EXISTS `act_ext_prop`;
CREATE TABLE `act_ext_prop`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `RELATION_ID` bigint(20) NULL DEFAULT NULL COMMENT '关联',
  `PROP_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '属性类型',
  `PROP_KEY` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '属性Key',
  `PROP_VALUE` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '属性Value',
  `IS_DELETED` bit(1) NOT NULL DEFAULT b'0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_RELATION_TYPE_KEY`(`RELATION_ID`, `PROP_TYPE`, `PROP_KEY`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 737 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '关联属性表 AMOUNT = 1000 SELECT = LOW INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_game_plane
-- ----------------------------
DROP TABLE IF EXISTS `act_game_plane`;
CREATE TABLE `act_game_plane`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户partyId',
  `DAY` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '日期',
  `SCORE` int(11) NULL DEFAULT 0 COMMENT '得分',
  `SHOT_COUNT` int(11) NULL DEFAULT 0 COMMENT '击落飞机数',
  `STAGE` int(11) NULL DEFAULT 0 COMMENT '过的关数',
  `COIN_REWARD` int(11) NULL DEFAULT 0 COMMENT '游戏内获取的金币',
  `STAGE_REWARD` int(11) NULL DEFAULT 0 COMMENT '钢卡奖励',
  `RANDOM_REWARD` int(11) NULL DEFAULT 0 COMMENT '随机奖励',
  `STATUS` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'I' COMMENT '状态',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `IDX_DAY`(`DAY`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 176 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '飞机大战战绩表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_group_balance_tran
-- ----------------------------
DROP TABLE IF EXISTS `act_group_balance_tran`;
CREATE TABLE `act_group_balance_tran`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TRAN_ID` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易号',
  `PARTY_ID` bigint(20) NULL DEFAULT NULL COMMENT '用户',
  `CHANGE_VALUE` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '变动金额',
  `TYPE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '类型',
  `SUB_TYPE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '子类型',
  `REMARK` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '备注信息',
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `IDX_TYPE`(`TYPE`) USING BTREE,
  INDEX `IDX_SUB_TYPE`(`SUB_TYPE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2567 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '交易明细' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_group_info
-- ----------------------------
DROP TABLE IF EXISTS `act_group_info`;
CREATE TABLE `act_group_info`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VERSION` int(11) NULL DEFAULT 1,
  `PARTY_ID` bigint(20) NULL DEFAULT NULL COMMENT '发起人',
  `STYLE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '团样式',
  `TOTAL_BALANCE` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '红包总金额',
  `STATUS` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态',
  `EXPIRE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '过期时间',
  `PARTNER` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '参与人员partyId拼接',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 320 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '团信息' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_group_info_detail
-- ----------------------------
DROP TABLE IF EXISTS `act_group_info_detail`;
CREATE TABLE `act_group_info_detail`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `INFO_ID` bigint(20) NULL DEFAULT NULL COMMENT '团id',
  `PARTY_ID` bigint(20) NULL DEFAULT NULL COMMENT '参与用户',
  `BALANCE` decimal(10, 2) NULL DEFAULT NULL COMMENT '分得金额',
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `IDX_INFO_ID`(`INFO_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 559 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '团员明细' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_group_tips
-- ----------------------------
DROP TABLE IF EXISTS `act_group_tips`;
CREATE TABLE `act_group_tips`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户',
  `TYPE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '类型',
  `TIPS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '信息累人',
  `CHANGE_VALUE` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '变动金额',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `IDX_TYPE`(`TYPE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1862 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '提示信息表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_group_user
-- ----------------------------
DROP TABLE IF EXISTS `act_group_user`;
CREATE TABLE `act_group_user`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VERSION` int(11) NULL DEFAULT 1,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户partyId',
  `MOBILE_PHONE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '手机号',
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '姓名',
  `HEAD_IMG` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '头像',
  `BALANCE` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '当前余额',
  `OPEN_ID` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '小程序openId',
  `UNION_ID` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '小程序unionid',
  `QR_CODE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '二维码地址',
  `POSTER_URL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '分享海报地址',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `IDX_MOBILE_PHONE`(`MOBILE_PHONE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 117 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '团参与用户' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_invite
-- ----------------------------
DROP TABLE IF EXISTS `act_invite`;
CREATE TABLE `act_invite`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户partyId',
  `USER_TYPE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '用户类型：区分普通用户，站长，员工',
  `NAME` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '姓名',
  `GENDER` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '性别',
  `AGE` int(11) NULL DEFAULT NULL COMMENT '年龄',
  `MOBILE_PHONE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '手机号',
  `PROVINCE` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '省',
  `CITY` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '市',
  `COUNTY` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '县',
  `TOWN` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '镇',
  `VILLAGE` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '村',
  `WX_INFO` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '微信信息',
  `NODE_MOBILE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '认识站长手机号',
  `SIGN_TIME` datetime(0) NULL DEFAULT NULL COMMENT '报名时间',
  `SOURCE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '来源',
  `EXPECT_NUM` int(255) NULL DEFAULT NULL COMMENT '期望邀请数',
  `INVITE_NUM` int(11) NULL DEFAULT NULL COMMENT '邀请数',
  `REGISTER_NUM` int(11) NULL DEFAULT NULL COMMENT '注册数',
  `ACTIVE_NUM` int(11) NULL DEFAULT NULL COMMENT '邀请活跃用户数',
  `PAST_ACTIVE_USER` int(11) NULL DEFAULT NULL COMMENT '昨日活跃用户',
  `PAST_ACTIVE_DEVICE` int(11) NULL DEFAULT NULL COMMENT '昨日活跃设备',
  `AUDDIT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '审核时间',
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'I' COMMENT '审核状态：初始，已通过，已拒绝',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 31 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '邀请活动主表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_invite_detail
-- ----------------------------
DROP TABLE IF EXISTS `act_invite_detail`;
CREATE TABLE `act_invite_detail`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL,
  `REC_PARTY_ID` bigint(20) NOT NULL,
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态：I：初始，S:成功',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_USER`(`PARTY_ID`, `REC_PARTY_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '邀请明细表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_plant
-- ----------------------------
DROP TABLE IF EXISTS `act_plant`;
CREATE TABLE `act_plant`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户',
  `LV` int(11) NOT NULL DEFAULT 0 COMMENT '当前爱心值',
  `TOTAL_LV` int(11) NOT NULL DEFAULT 0 COMMENT '总爱心值',
  `POSTER` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '海报地址',
  `QR` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '个人二维码地址',
  `OPEN_ID` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '微信openId',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 105 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '植树活动主表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_plant_lv
-- ----------------------------
DROP TABLE IF EXISTS `act_plant_lv`;
CREATE TABLE `act_plant_lv`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户',
  `LV` int(11) NOT NULL DEFAULT 0 COMMENT '当前爱心值',
  `TOTAL_LV` int(11) NULL DEFAULT 0 COMMENT '总爱心值',
  `TYPE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '类型，区分来源，任务，注册，奖励',
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态',
  `SHOU_TIME` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始显示时间',
  `MATURE_TIME` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '可领取时间',
  `EXPIRE_TIME` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '过期时间',
  `TASK_ID` bigint(11) NULL DEFAULT NULL COMMENT '关联的任务id',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_TASK_ID`(`TASK_ID`) USING BTREE,
  INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `IDX_TYPE`(`TYPE`) USING BTREE,
  INDEX `IDX_SHOU_TIME`(`SHOU_TIME`) USING BTREE,
  INDEX `IDX_MATURE_TIME`(`MATURE_TIME`) USING BTREE,
  INDEX `IDX_EXPIRE_TIME`(`EXPIRE_TIME`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 26152 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '植树活动爱心表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_plant_lv_tran
-- ----------------------------
DROP TABLE IF EXISTS `act_plant_lv_tran`;
CREATE TABLE `act_plant_lv_tran`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NULL DEFAULT NULL COMMENT '用户',
  `LV_ID` bigint(20) NULL DEFAULT NULL COMMENT '关联爱心id',
  `LV` int(11) NULL DEFAULT 0 COMMENT '爱心值',
  `TYPE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '类型，区分操作，收取，偷取，兑换',
  `PRIZE_CODE` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品CODE',
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品名',
  `USER_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收货用户名',
  `MOBILE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收货手机号',
  `ADDRESS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收货地址',
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态',
  `REMARK` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '客服备注',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_PARTY_ID_LVID`(`PARTY_ID`, `LV_ID`) USING BTREE,
  INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `IDX_TYPE`(`TYPE`) USING BTREE,
  INDEX `IDX_STATUS`(`STATUS`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1967 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '爱心交易明细' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_plant_notice
-- ----------------------------
DROP TABLE IF EXISTS `act_plant_notice`;
CREATE TABLE `act_plant_notice`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOTICE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '公告内容',
  `LINK` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '链接地址',
  `START_TIME` datetime(0) NULL DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime(0) NULL DEFAULT NULL COMMENT '结束时间',
  `CREATOR` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 18 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '福利树公告表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_plant_prize
-- ----------------------------
DROP TABLE IF EXISTS `act_plant_prize`;
CREATE TABLE `act_plant_prize`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品code',
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '奖品名',
  `IMAGE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '奖品图片',
  `LV` int(11) NOT NULL DEFAULT 0 COMMENT '奖品爱心值',
  `TYPE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '类型，区分兑换奖品和奖励',
  `REWARD_TYPE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '类型，区分金币',
  `GOLD` int(11) NULL DEFAULT 0 COMMENT '金币数',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 16 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '奖励' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_plant_task
-- ----------------------------
DROP TABLE IF EXISTS `act_plant_task`;
CREATE TABLE `act_plant_task`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '任务code',
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '任务名',
  `IMAGE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '任务图片',
  `DETAIL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '描述',
  `DAY_LIMIT` int(11) NULL DEFAULT NULL COMMENT '每日上限',
  `TYPE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '类型',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 19 CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_plant_task_detail
-- ----------------------------
DROP TABLE IF EXISTS `act_plant_task_detail`;
CREATE TABLE `act_plant_task_detail`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户',
  `CODE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '任务code',
  `DAY` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '日期 YYYYMMDD',
  `TYPE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '类型',
  `REF_ID` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '关联数据id',
  `STATUS` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `IDX_DAY`(`DAY`) USING BTREE,
  INDEX `IDX_TYPE`(`TYPE`) USING BTREE,
  INDEX `IDX_REF_ID`(`REF_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 303 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '任务进度' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_plant_tip
-- ----------------------------
DROP TABLE IF EXISTS `act_plant_tip`;
CREATE TABLE `act_plant_tip`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户partyId',
  `TYPE` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '类型',
  `TIP` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '提示信息',
  `STATUS` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'S' COMMENT '消息消费状态：SL已消费，I：初始状态',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_PARTY_ID`(`PARTY_ID`) USING BTREE,
  INDEX `IDX_TYPE`(`TYPE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 379 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '消息提示表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_pop_window
-- ----------------------------
DROP TABLE IF EXISTS `act_pop_window`;
CREATE TABLE `act_pop_window`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ACTIVITY_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动名称',
  `EVENT_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '弹窗事件code，一般使用mq 的topic 和 tag组合',
  `TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '弹窗类型，BY_TIME/BY_EVENT',
  `TEMPLATE_CODE` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '弹框类型',
  `SHOW_START_TIME` datetime(0) NULL DEFAULT NULL COMMENT '弹窗开始时间',
  `SHOW_EXPIRE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '弹框结束时间',
  `ACTIVITY_LOGO` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动LOGO',
  `ACTIVITY_LOGO_DEST_URL` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动LOGO跳转URL',
  `LEFT_BUTTON_URL` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '左边按钮url',
  `RIGHT_BUTTON_URL` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '右边按钮url',
  `FREQUENCY` int(11) NULL DEFAULT NULL COMMENT '弹窗频率',
  `ORDER_NUM` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '排序',
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 51 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '活动弹窗表 AMOUNT = 1000 SELECT = HIGH INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_pop_window_history
-- ----------------------------
DROP TABLE IF EXISTS `act_pop_window_history`;
CREATE TABLE `act_pop_window_history`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `POP_WINDOW_ID` bigint(20) NULL DEFAULT NULL COMMENT '弹框ID',
  `PARTY_ID` bigint(20) NULL DEFAULT NULL COMMENT '用户partyId',
  `POP_DATE` datetime(0) NULL DEFAULT NULL COMMENT '弹框时间',
  `TEMPLATE_CODE` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '弹框类型',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3297 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '活动弹窗历史表 AMOUNT = 1000 SELECT = HIGH INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_prize
-- ----------------------------
DROP TABLE IF EXISTS `act_prize`;
CREATE TABLE `act_prize`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ACTIVITY_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动标签',
  `PRIZE_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品标签',
  `PRIZE_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品发放类型 金币/电商优惠券/微信红包等',
  `PRIZE_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品名称',
  `PRIZE_IMAGE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品图片',
  `COUPON_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '优惠券名称',
  `PRIZE_LEVEL` int(11) NULL DEFAULT NULL COMMENT '奖品等级',
  `UNIT_RMB` decimal(10, 2) NULL DEFAULT NULL COMMENT '换算成人民币的单位',
  `PRIZE_DESC` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品描述',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 121 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '活动奖品定义表 AMOUNT = 1000 SELECT = LOW INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_prize_config
-- ----------------------------
DROP TABLE IF EXISTS `act_prize_config`;
CREATE TABLE `act_prize_config`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `PRIZE_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品标签',
  `CUSTOMER_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户类型（新用户/老用户）',
  `START_DATE` datetime(0) NULL DEFAULT NULL COMMENT '活动分布开始时间',
  `EXPIRE_DATE` datetime(0) NULL DEFAULT NULL COMMENT '活动分布结束日期',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 13 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '活动奖品配置 AMOUNT = 1000 SELECT = LOW INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_prize_probability_config
-- ----------------------------
DROP TABLE IF EXISTS `act_prize_probability_config`;
CREATE TABLE `act_prize_probability_config`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `PRIZE_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品标签',
  `CUSTOMER_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户类型（新用户/老用户）',
  `INITIAL_PROBABILITY` decimal(8, 7) NULL DEFAULT NULL COMMENT '初始得奖概率',
  `ADD_PROBABILITY` decimal(8, 7) NULL DEFAULT NULL COMMENT '提升后得奖概率',
  `INCREMENT` decimal(8, 7) NULL DEFAULT NULL COMMENT '增量',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '大奖概率配置 AMOUNT = 1000 SELECT = LOW INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_public_sequence
-- ----------------------------
DROP TABLE IF EXISTS `act_public_sequence`;
CREATE TABLE `act_public_sequence`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 14128 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '公共自增序列 AMOUNT = 1000000 SELECT = HIGH INSERT = HIGH UPDATE = LOW' ROW_FORMAT = Fixed;

-- ----------------------------
-- Table structure for act_red_packet
-- ----------------------------
DROP TABLE IF EXISTS `act_red_packet`;
CREATE TABLE `act_red_packet`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `PACKET_ID` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '红包唯一标识',
  `PARTY_ID` bigint(20) NOT NULL COMMENT '分享者partyId',
  `IS_COMPLETE` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT 'N' COMMENT '是否成团',
  `START_DATE` datetime(0) NOT NULL COMMENT '开始时间',
  `COMPLETE_DATE` datetime(0) NULL DEFAULT NULL COMMENT '完成时间',
  `EXPIRE_DATE` datetime(0) NULL DEFAULT NULL COMMENT '有效时间',
  `IS_CHECKED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '是否通过验证的/签到/晒收入/发微博',
  `PACKET_INFO` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '红包描述信息',
  `MEMC_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '订单编号/优惠卷码',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '51红包 团 AMOUNT = 1000 SELECT = HIGH INSERT = HIGH UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_red_packet_partaker
-- ----------------------------
DROP TABLE IF EXISTS `act_red_packet_partaker`;
CREATE TABLE `act_red_packet_partaker`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `PACKET_ID` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '红包唯一标识',
  `PARTY_ID` bigint(20) NOT NULL COMMENT '参与者partyId',
  `MOBILE_PHONE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '参与者手机号',
  `USER_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户类型/未注册APP和已经注册APP',
  `HEAD_IMG` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '随机头像',
  `DEVICE_ID` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '设备编号',
  `WX_OPEN_ID` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'openId',
  `OPEN_DATE` datetime(0) NOT NULL COMMENT '开奖时间',
  `IS_REMIND` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N' COMMENT '是否已经提示中奖',
  `PRIZE_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '奖品code',
  `PRIZE_VALUE` decimal(16, 5) NULL DEFAULT NULL COMMENT '奖品价值/换算成rmb，24内注册app可领取',
  `MEMC_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '订单编号/优惠卷码',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '51红包 开团 参与者 AMOUNT = 1000 SELECT = HIGH INSERT = HIGH UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_red_packet_sharer
-- ----------------------------
DROP TABLE IF EXISTS `act_red_packet_sharer`;
CREATE TABLE `act_red_packet_sharer`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `PARTY_ID` bigint(20) NOT NULL COMMENT '分享者partyId',
  `MOBILE_PHONE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '分享者手机号',
  `DEVICE_ID` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '设备编号',
  `WX_OPEN_ID` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'openId',
  `WX_HEAD_IMG` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '微信头像',
  `WX_NICK_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '昵称',
  `SHARER_QR_CODE` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '二维码code',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '51活动分享者 AMOUNT = 1000 SELECT = HIGH INSERT = HIGH UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_sign_times
-- ----------------------------
DROP TABLE IF EXISTS `act_sign_times`;
CREATE TABLE `act_sign_times`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `RELATION_ID` bigint(20) NULL DEFAULT NULL COMMENT '关联',
  `PROP_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '属性类型',
  `PROP_KEY` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '属性Key',
  `PROP_VALUE` int(11) NULL DEFAULT NULL COMMENT '属性Value',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `INX#SIGN#RELATION_ID`(`RELATION_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 714 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '打卡天数计数表  AMOUNT = 1000 SELECT = LOW INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_step_detail
-- ----------------------------
DROP TABLE IF EXISTS `act_step_detail`;
CREATE TABLE `act_step_detail`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PARTY_ID` bigint(20) NOT NULL COMMENT '用户partyId',
  `DAY` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '日期  YYYYMMDD格式',
  `TYPE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '类型，区分四个时间段及全部',
  `STEP_NUMBER` int(11) NOT NULL DEFAULT 0 COMMENT '步数',
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT 'I' COMMENT '状态',
  `GOLD_REWARD` int(11) NOT NULL DEFAULT 0 COMMENT '金币奖励数',
  `REWARD_TIME` datetime(0) NULL DEFAULT NULL COMMENT '金币兑换时间',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_UNIQ`(`PARTY_ID`, `DAY`, `TYPE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1061 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '步步生金活动明细' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_system_config
-- ----------------------------
DROP TABLE IF EXISTS `act_system_config`;
CREATE TABLE `act_system_config`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `CONFIG_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '配置code',
  `CONFIG_VALUE` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `CONFIG_DESC` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '描述',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 100 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '活动系统的一些配置表 AMOUNT = 1000 SELECT = LOW INSERT = LOW UPDATE = LOW' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_vote_activity_ext
-- ----------------------------
DROP TABLE IF EXISTS `act_vote_activity_ext`;
CREATE TABLE `act_vote_activity_ext`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ACTIVITY_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '关联act_activity中的记录',
  `CAROUSEL_IMGS` varchar(4096) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '轮播图图片',
  `DISPLAY_DATE` datetime(0) NULL DEFAULT NULL COMMENT '活动结束开始展示',
  `VOTE_MODE` int(11) NULL DEFAULT NULL COMMENT '投票形式 0:每日均可投票，1:一次性投票',
  `EVETY_DAY_VOTES` int(11) NULL DEFAULT NULL COMMENT '每人每天可投票数 VOTE_MODE 为0时可用',
  `ALL_VOTES` int(11) NULL DEFAULT NULL COMMENT '每人可投票数 VOTE_MODE 为1时可用',
  `SHARE_ICON` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '分享icon',
  `SHARE_TITLE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '分享标题',
  `SHARE_SUB_TITLE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '分享子标题',
  `SHARE_URL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '分享url',
  `AWARD_DESC` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '活动奖励',
  `DESC_FOOTER` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动说明页脚',
  `ACT_DESC` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '活动介绍',
  `VOTE_DESC` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '投票须知',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '投票活动拓展表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_vote_item
-- ----------------------------
DROP TABLE IF EXISTS `act_vote_item`;
CREATE TABLE `act_vote_item`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ORDER_NUMBER` int(11) NULL DEFAULT NULL COMMENT '序号',
  `ACTIVITY_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '投票活动code',
  `PARTY_ID` bigint(20) UNSIGNED NULL DEFAULT NULL COMMENT 'partyId',
  `STATUS` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态',
  `IMAGES` varchar(2046) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '图片，保证容量冗余',
  `DESCRIPTION` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '描述',
  `BASE_VOTE_NUM` int(11) NULL DEFAULT NULL COMMENT '基础投票数，用于票数显示假数据',
  `REAL_VOTE_NUM` int(11) NULL DEFAULT NULL COMMENT '真实投票数的冗余字段',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `INX#VITEM#PARTYID`(`PARTY_ID`) USING BTREE,
  INDEX `UK_ORER_ACTIVITY`(`ORDER_NUMBER`, `ACTIVITY_CODE`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 637 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '投票活动投票目标表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for act_vote_rel
-- ----------------------------
DROP TABLE IF EXISTS `act_vote_rel`;
CREATE TABLE `act_vote_rel`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `PARTY_ID` bigint(20) UNSIGNED NULL DEFAULT NULL COMMENT 'partyId',
  `ACTIVITY_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '活动code',
  `TO_PARTY_ID` bigint(20) NULL DEFAULT NULL COMMENT '关联act_vote_target中的记录',
  `USER_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '当次投票时用户类型，表明是新用户或者老用户',
  `STATUS` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '状态',
  `AMOUNT` decimal(10, 2) NULL DEFAULT NULL COMMENT '金额（金币）',
  `AWARD_AMOUNT` decimal(10, 2) NULL DEFAULT NULL COMMENT '获得的金额（金币）',
  `IS_DELETED` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '0' COMMENT '统一删除标记',
  `CREATOR` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `UPDATER` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `CREATE_DATE` datetime(0) NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `INX#VREL#PARTY_ID`(`PARTY_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 446 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '用户投票表' ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for tmp_app_user
-- ----------------------------
DROP TABLE IF EXISTS `tmp_app_user`;
CREATE TABLE `tmp_app_user`  (
  `ID` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `LOGIN_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '登陆名',
  `PARTY_ID` bigint(20) NOT NULL COMMENT '关联的parityId',
  `USER_TYPE` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户类型，区分站长和村民',
  `DEVICE_ID` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `SESSION_ID` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'SESSIONID',
  `NIKER_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '昵称',
  `HEAD_IMG` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '头像',
  `INTRODUCE` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '个人介绍',
  `TRUE_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '真实姓名，和cif同步',
  `DESCS` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '扩展信息，json格式',
  `PASSWORD` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户密码',
  `PASSWORD_SALT` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '密码盐',
  `PASSWORD_PATTERN_STATUS` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '图形密码状态（Y:开启，N:关闭）',
  `PASSWORD_PATTERN` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '图形密码',
  `RY_TOKEN` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '融云token',
  `PROVINCE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '省',
  `CITY` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '市',
  `COUNTY` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '县、区',
  `TOWN` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '镇',
  `VILLAGE` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '村名',
  `DISTRICT` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '区域合计，家乡',
  `GENDER` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '性别',
  `LOCATION` varchar(512) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '所在地',
  `BIRTHDAY` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '生日',
  `REC_USER_PARTY_ID` bigint(20) NULL DEFAULT NULL COMMENT '推荐人partyId',
  `STATUS` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户状态',
  `IS_DELETED` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT 'N',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL,
  `UPDATE_TIME` datetime(0) NULL DEFAULT NULL,
  `COMMENTS` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Compact;

-- ----------------------------
-- Function structure for fakeDate
-- ----------------------------
DROP FUNCTION IF EXISTS `fakeDate`;
delimiter ;;
CREATE DEFINER=`xlactuser`@`%` FUNCTION `fakeDate`(dateStr DATETIME, t INT) RETURNS varchar(2) CHARSET utf8 COLLATE utf8_bin
BEGIN
    DECLARE i INT;
    SET i = 1;
    DELETE FROM xlactdb.act_customer_acquire_record;
    WHILE i <= t DO
      #插入数据
      INSERT INTO xlactdb.act_customer_acquire_record (ID, PARTY_ID, USER_NAME, USER_TYPE, ACTIVITY_CODE, MOBILE_PHONE, HEAD_IMAGE_URL, ACTIVITY_FEE, PRIZE_CODE, PRIZE_VALUE, MEMC_CODE, ACQUIRE_DATE, SIGN_IN_DATE, STATUS, IS_DELETED, CREATOR, UPDATER, CREATE_DATE, UPDATE_DATE, COMMENTS)
        SELECT
          NULL,
          concat(i, PARTY_ID),
          NIKER_NAME,
          'ATTENDANCE_USER',
          'ATTENDANCE_AWARD',
          LOGIN_NAME,
          HEAD_IMG,
          100.00000,
          NULL,
          NULL,
          NULL,
          NULL,
          CONCAT(date_format(dateStr, '%y-%m-%d'),
                 ' ',
                 CEIL(RAND() * 2) + 5,
                 ':',
                 CEIL(RAND() * 60 - 1),
                 ':',
                 CEIL(RAND() * 60) - 1),
          'SIGN_IN',
          '0',
          'system',
          'system',
          now(),
          now(),
          'mock_打卡赢金币'
        FROM tmp_app_user
        LIMIT 106;
      #######更新时间
      UPDATE act_customer_acquire_record record
      SET record.CREATE_DATE = date_add(SIGN_IN_DATE, INTERVAL -1 DAY), UPDATE_DATE = SIGN_IN_DATE
      WHERE COMMENTS = 'mock_打卡赢金币' AND DATEDIFF(SIGN_IN_DATE, dateStr) = 0;
      SET i = i + 1;
    END WHILE;
    RETURN 'OK';
  END
;;
delimiter ;

-- ----------------------------
-- Function structure for getseq
-- ----------------------------
DROP FUNCTION IF EXISTS `getseq`;
delimiter ;;
CREATE DEFINER=`xlactuser`@`%` FUNCTION `getseq`() RETURNS bigint(20)
    COMMENT '从 act_public_sequence 表中获取自增长序列'
BEGIN
    INSERT INTO act_public_sequence (ID) VALUES (NULL);
    RETURN (LAST_INSERT_ID());
  END
;;
delimiter ;

-- ----------------------------
-- Function structure for mockUser
-- ----------------------------
DROP FUNCTION IF EXISTS `mockUser`;
delimiter ;;
CREATE DEFINER=`xlactuser`@`%` FUNCTION `mockUser`(users INT) RETURNS varchar(10) CHARSET utf8 COLLATE utf8_bin
BEGIN
    DECLARE _PARTY_ID BIGINT UNSIGNED;
    DECLARE i INT;
    UPDATE act_customer_acquire_record
    SET PRIZE_CODE = NULL, PRIZE_VALUE = NULL, STATUS = 'SIGN_IN', ACQUIRE_DATE = NULL, IS_DELETED = 1;
    SET i = 1;
    WHILE i <= users DO
      SET _PARTY_ID = (SELECT ID
                       FROM act_customer_acquire_record
                       WHERE IS_DELETED = 1
                       ORDER BY RAND()
                       LIMIT 1);
      UPDATE act_customer_acquire_record
      SET IS_DELETED = 0
      WHERE id = _PARTY_ID;
      SET i = i + 1;
    END WHILE;
    RETURN 'OK';
  END
;;
delimiter ;

-- ----------------------------
-- Function structure for updateActDays
-- ----------------------------
DROP FUNCTION IF EXISTS `updateActDays`;
delimiter ;;
CREATE DEFINER=`xlactuser`@`%` FUNCTION `updateActDays`(days INT) RETURNS varchar(10) CHARSET utf8 COLLATE utf8_bin
BEGIN
    DECLARE act_time DATETIME;
    SET act_time = DATE_SUB(now(), INTERVAL days - 1 DAY);
    UPDATE act_activity
    SET START_DATE = act_time
    WHERE ACTIVITY_CODE = 'ATTENDANCE_AWARD';
    RETURN 'OK';
  END
;;
delimiter ;

-- ----------------------------
-- Event structure for syn_dev
-- ----------------------------
DROP EVENT IF EXISTS `syn_dev`;
delimiter ;;
CREATE DEFINER = `xlactuser`@`%` EVENT `syn_dev`
ON SCHEDULE
EVERY '1' MINUTE STARTS '2018-10-01 10:59:34'
ON COMPLETION PRESERVE
DO update act_invite A,
(select REC_PARTY_ID,count(*) as COUNT from act_invite_detail where IS_DELETED = 'N' and `STATUS` = 'S' GROUP BY REC_PARTY_ID) B
set A.REGISTER_NUM = B.COUNT where A.PARTY_ID = B.REC_PARTY_ID
;;
delimiter ;

SET FOREIGN_KEY_CHECKS = 1;
